name: Playwright Tests with Allure Report

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Install Playwright browsers
        working-directory: Playwright.Tests
        run: |
          dotnet build --configuration Release
          pwsh bin/Release/net9.0/playwright.ps1 install --with-deps

      - name: Run Playwright tests
        env:
          ORANGEHRM_URL: ${{ secrets.ORANGEHRM_URL }}
          ORANGEHRM_USER: ${{ secrets.ORANGEHRM_USER }}
          ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}
        run: |
          dotnet test Playwright.Tests/Playwright.Tests.csproj \
            --configuration Release \
            --no-build \
            --settings prod.runsettings || true  # prevents job failure

      - name: Install Allure commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz -O allure.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Verify Allure installation
        run: allure --version

      - name: Check if allure-results exists
        if: always()
        run: |
          echo "Checking allure-results..."
          if [ -d "Playwright.Tests/bin/Release/net9.0/allure-results" ]; then
            echo "✅ allure-results found."
          else
            echo "⚠️ allure-results folder missing, creating empty one."
            mkdir -p Playwright.Tests/bin/Release/net9.0/allure-results
          fi

      - name: Generate Allure HTML report
        if: always()
        run: |
          allure generate --clean \
            -o Playwright.Tests/bin/Release/net9.0/allure-report \
            Playwright.Tests/bin/Release/net9.0/allure-results || echo "No allure results found"

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: Playwright.Tests/bin/Release/net9.0/allure-report
          if-no-files-found: warn  # allow missing reports but still continue

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Checkout repository (clean)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
          path: repo

      - name: Remove existing gh-pages branch content
        working-directory: repo
        run: |
          git fetch origin gh-pages || true
          git switch --orphan gh-pages
          git rm -rf . || true
          rm -rf ./*
          echo "✅ gh-pages branch cleaned."

      - name: Download Allure artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./AllureReport

      - name: Verify Allure report contents
        run: |
          echo "=== Checking Allure report folder ==="
          pwd
          ls -R ./AllureReport || true

          if [ ! -d "./AllureReport" ] || [ -z "$(ls -A ./AllureReport)" ]; then
            echo "❌ No report files found — skipping deployment."
            exit 1
          else
            echo "✅ Allure report found and ready for deployment."
          fi

      - name: Deploy to GitHub Pages (force overwrite)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./AllureReport
          force_orphan: true
          enable_jekyll: false
          keep_files: false
          user_name: vokut
          user_email: vokut@users.noreply.github.com

      - name: Add report link to summary
        if: always()
        run: |
          echo "✅ [View Latest Allure Report](https://vokut.github.io/PlaywrightSolution/)" >> $GITHUB_STEP_SUMMARY